name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 44.206.95.4
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use --lts

            cd /home/ubuntu/Safetrack
            git fetch --all
            git reset --hard origin/main

            cd backend

            npm install

            pm2 delete app || true
            pm2 start app.js --name app