# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: 44.206.95.4
#           username: ubuntu
#           key: ${{ secrets.EC2_SSH_KEY }}
#           debug: true
#           script: |
#             cd /home/ubuntu/Safetrack
#             git fetch --all
#             git reset --hard origin/main

#             # 啟用 Python venv
#             source venv/bin/activate

#             # 安裝套件（如果有 requirements.txt）
#             pip install -r requirements.txt || true

#             # 重啟服務
#             pkill -f uvicorn || true
#             nohup uvicorn main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 < /dev/null &